name: Publish

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24"
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Set version from tag
        run: npm version "${GITHUB_REF_NAME#v}" --no-git-tag-version
      - run: npm publish --access public
